### ISSUE TITLE
Manager

### ISSUE THREAD

**Issue by AndaleObe** [skyre5/Elite-Hockey-Manager#3]
Top 👍🏻

**Comment by skyre5** [comment]
hey @AndaleObe 

Adding 150 teams should be possible with some small changes. The UI would have to be redesigned though to fit that many teams on all the components that show them. Also the playoffs are only designed for up to 16 teams so that would have to be expanded upon probably.

Adding settings to turn off free agency and player aging would also probably be an easy addition but not currently available. It'd probably be set when creating the league and carried throughout as a setting with the League class.

**Comment by AndaleObe** [comment]
> hey @AndaleObe
> 
> Adding 150 teams should be possible with some small changes. The UI would have to be redesigned though to fit that many teams on all the components that show them. Also the playoffs are only designed for up to 16 teams so that would have to be expanded upon probably.
> 
> Adding settings to turn off free agency and player aging would also probably be an easy addition but not currently available. It'd probably be set when creating the league and carried throughout as a setting with the League class.

free agency should not be deactivated. just drafting and aging players. I would just do a pure simulation without the games and playoffs taking place. just simulating contracts and player commitments. but I can't get the manager to work in visual studio. I download the netgui packages but when debugging I get the error message that no .exe is available

**Comment by skyre5** [comment]
@AndaleObe Hopefully I fixed the issue with getting it working. That functionality could definitely be added but it'd probably be best added as a separate mode on the main menu. Also the contract and player movements are somewhat barebones currently. The salary cap isn't enforced and there are no trades. The player movement in the offseason is just random I believe.

**Comment by AndaleObe** [comment]
> @AndaleObe Hopefully I fixed the issue with getting it working. That functionality could definitely be added but it'd probably be best added as a separate mode on the main menu. Also the contract and player movements are somewhat barebones currently. The salary cap isn't enforced and there are no trades. The player movement in the offseason is just random I believe.

The fact that the player movements are random is brilliant. fantasy is exactly what I'm looking for. The background is, I play NHL on the PS4 and I would use a tool to create all the teams with players. I play the European leagues. DEL, SHL, Liiga, IceHL etc. the tool carries out transfers and I then transfer the player changes to the NHL game
